"""Local installation/bootstrap helper for LongFact.

This script prepares a Windows local environment by optionally installing Python
dependencies, writing a project-local `.env.local` configuration file, and warming
the HuggingFace caches for the GovReport dataset and the default models.
"""
from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path
from typing import Dict, Iterable, Optional

from config import (
    DEFAULT_CORRECTOR_MODEL,
    DEFAULT_DATA_DIR,
    DEFAULT_GOVREPORT_DATASET,
    DEFAULT_GOVREPORT_SPLIT,
    DEFAULT_NLI_MODEL,
    DEFAULT_OUTPUT_DIR,
    DEFAULT_RETRIEVER_MODEL,
    DEFAULT_SUMMARIZER_MODEL,
    PROJECT_ROOT,
    ensure_local_dirs,
)

try:
    from datasets import load_dataset
except Exception as e:
    load_dataset = None
    import traceback
    print('bootstrap_local: datasets import failed:', e)
    traceback.print_exc()

try:
    from huggingface_hub import snapshot_download
except Exception as e:
    snapshot_download = None
    import traceback
    print('bootstrap_local: huggingface_hub import failed:', e)
    traceback.print_exc()


def write_env_file(env_path: Path, values: Dict[str, str]) -> None:
    lines = ["# Auto-generated by bootstrap_local.py"]
    for key, value in values.items():
        lines.append(f"{key}={value}")
    env_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def install_requirements(requirements_path: Path) -> None:
    subprocess.run([sys.executable, "-m", "pip", "install", "-r", str(requirements_path)], check=True)


def warm_dataset(dataset_name: str, split: str, cache_dir: Path) -> None:
    if load_dataset is None:
        raise ImportError("datasets is required to warm the GovReport dataset cache")
    load_dataset(dataset_name, split=split, cache_dir=str(cache_dir))


def warm_model(repo_id: str, cache_dir: Path) -> None:
    if snapshot_download is None:
        raise ImportError("huggingface_hub is required to pre-download model repositories")
    snapshot_download(repo_id=repo_id, cache_dir=str(cache_dir))


def iter_default_models() -> Iterable[str]:
    yield DEFAULT_SUMMARIZER_MODEL
    yield DEFAULT_NLI_MODEL
    yield DEFAULT_CORRECTOR_MODEL
    yield DEFAULT_RETRIEVER_MODEL


def main() -> None:
    parser = argparse.ArgumentParser(description="Prepare LongFact for local use.")
    parser.add_argument("--install-deps", action="store_true", help="Install requirements from requirements.txt")
    parser.add_argument("--download-dataset", action="store_true", help="Warm the GovReport dataset cache")
    parser.add_argument("--download-models", action="store_true", help="Pre-download the default HuggingFace models")
    parser.add_argument("--write-env", action="store_true", help="Write a project-local .env.local file")
    parser.add_argument("--dataset-name", type=str, default=DEFAULT_GOVREPORT_DATASET)
    parser.add_argument("--dataset-split", type=str, default=DEFAULT_GOVREPORT_SPLIT)
    parser.add_argument("--cache-dir", type=str, default=str(DEFAULT_DATA_DIR))
    parser.add_argument("--output-dir", type=str, default=str(DEFAULT_OUTPUT_DIR))
    parser.add_argument("--models", nargs="*", default=None, help="Optional explicit model repo IDs to download")
    args = parser.parse_args()

    if not any([args.install_deps, args.download_dataset, args.download_models, args.write_env]):
        args.install_deps = True
        args.download_dataset = True
        args.download_models = True
        args.write_env = True

    cache_dir = Path(args.cache_dir)
    output_dir = Path(args.output_dir)
    ensure_local_dirs()
    cache_dir.mkdir(parents=True, exist_ok=True)
    output_dir.mkdir(parents=True, exist_ok=True)

    if args.write_env:
        env_path = PROJECT_ROOT / ".env.local"
        write_env_file(
            env_path,
            {
                "LONGFACT_DATA_DIR": str(cache_dir),
                "LONGFACT_OUTPUT_DIR": str(output_dir),
                "LONGFACT_GOVREPORT_DATASET": args.dataset_name,
                "LONGFACT_GOVREPORT_SPLIT": args.dataset_split,
                "LONGFACT_SUMMARIZER_MODEL": DEFAULT_SUMMARIZER_MODEL,
                "LONGFACT_NLI_MODEL": DEFAULT_NLI_MODEL,
                "LONGFACT_CORRECTOR_MODEL": DEFAULT_CORRECTOR_MODEL,
                "LONGFACT_RETRIEVER_MODEL": DEFAULT_RETRIEVER_MODEL,
                "HF_HOME": str(PROJECT_ROOT / ".hf-cache"),
                "HF_DATASETS_CACHE": str(cache_dir / "datasets"),
                "HUGGINGFACE_HUB_CACHE": str(PROJECT_ROOT / ".hf-cache" / "hub"),
                "TRANSFORMERS_CACHE": str(PROJECT_ROOT / ".hf-cache" / "transformers"),
                "SENTENCE_TRANSFORMERS_HOME": str(PROJECT_ROOT / ".hf-cache" / "sentence-transformers"),
            },
        )
        print(f"Wrote {env_path}")

    if args.install_deps:
        install_requirements(PROJECT_ROOT / "requirements.txt")
        print("Installed Python dependencies")

    if args.download_dataset:
        warm_dataset(args.dataset_name, args.dataset_split, cache_dir)
        print(f"Cached dataset {args.dataset_name} [{args.dataset_split}]")

    if args.download_models:
        model_ids = list(args.models) if args.models else list(iter_default_models())
        for model_id in model_ids:
            download_id = "sentence-transformers/all-MiniLM-L6-v2" if model_id == DEFAULT_RETRIEVER_MODEL else model_id
            warm_model(download_id, Path(PROJECT_ROOT / ".hf-cache"))
            print(f"Cached model {model_id}")

    print("Local bootstrap complete.")


if __name__ == "__main__":
    main()